#@knooooot 05/11/2026 Feel free to change this I am bad at coding.
name: Validate drugs.json changes

on:
  push:

jobs:
  validate-jsons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Start Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install AJV
        run: npm install -g ajv-cli@>=8.20.0

      - name: Install AJV Formats
        run: npm install ajv-formats

      - name: Validate JSON files
        run: |
          export PATH="$PATH:./node_modules/.bin"  # Add node_modules/.bin to PATH
          for file in drug_files/*.json; do
            echo "Validating: $file"
            ajv validate -s 'schemas/drugs-schema.json' -d "$file" --formats ajv-formats
            if [ $? -ne 0 ]; then
              echo "Validation failed for $file"
              exit 1  # Exit the workflow if validation fails
            fi
          done

      - name: Build drugs.json
        if: success()
        run: npx ts-node ./scripts/your_script.ts