#@knooooot 05/11/2026 Feel free to change this I am bad at coding.
name: Validate drugs.json changes

on:
 push:

jobs:
 validate-jsons:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v6

   - name: Start Node.js
     uses: actions/setup-node@v4
     with:
      node-version: '21'

   - name: Install AJV
     run: npm install -g ajv-cli

   - name: Validate JSON files 
     run: |
      echo "test"
      for file in drug_files/*.json; do
      echo "Validating2 $file"
      echo string.format(./schemas/drugs-schema.json)
      ajv validate -s 'schemas/drugs-schema.json' -d "$file"
      done
      on-error:
      message: {{error.message}}
      continue
      }

   - name: Build drugs.json
     if: success()
     run: npx ts-node ./scripts/
